### ISSUE TITLE
404 page seems to be broken

### ISSUE THREAD

**Issue by kyu08** [ratatui/ratatui-website#160] opened 2023-11-19 15:16 UTC
When I accessed to not existing page like https://ratatui.rs/tutorial/non-existing-page, my browser shows me this.

<img width="218" alt="image" src="https://github.com/ratatui-org/ratatui-book/assets/49891479/8aa6178c-519d-4074-b129-ef91ebdaf016">

**Comment by kdheepak** [comment] 2023-11-19 15:59
I think the problem is this link:

https://github.com/ratatui-org/ratatui-book/blob/6ef92b25648fa4db2d74179f17d0eb5f6256f18e/404.html#L7

**Comment by kdheepak** [comment] 2023-11-19 16:01
I think this will be fixed shortly:

https://github.com/ratatui-org/ratatui-book/blob/6ef92b25648fa4db2d74179f17d0eb5f6256f18e/pr-preview/pr-163/404.html#L7

**Closed as completed** 2023-11-19 16:04 UTC

**Comment by kyu08** [comment] 2023-11-19 16:07
Thank you for fixing this issue so quickly 💯 :)
